steps:                                              
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'us-docker.pkg.dev/cloudrun/container:latest', '.']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'us-docker.pkg.dev/cloudrun/container:latest']
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'my-cloudrun-service'
      - '--image=gcr.io/safes-project/hello'
      - '--platform=managed'
      - '--region=us-east1'
options:
  logging: CLOUD_LOGGING_ONLY